import type { Metadata } from "next";
import {ClerkProvider} from '@clerk/nextjs'
import {ConvexClientProvider} from "@/providers/ConvexClientProvider"
import "./globals.css";


export const metadata: Metadata = {
  title: "Link Tree Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
